### ISSUE TITLE
Setting up

### ISSUE THREAD

**Issue by VaishMadh** [dougspeed/LDAK#3]
Hi Doug, I apologise if this is a basic question, but I couldn't find help anywhere else, so I had to pose this question to you.
I downloaded the ldak6.linux file and uploaded it onto my Linux environment. Then I ran chmod a+x ldak6.linux and ./ldak6.linux (using the full file path) and this is the message that was displayed: 
![LDAK message](https://github.com/user-attachments/assets/0c94cb29-fcaa-4fe9-88e1-94cc6a417c8c)

And the list of arguments was given. I tried using ldak --help but it said "command not found", so I'm assuming it is still not set up. Can you please let me know how to troubleshoot this? 

Best,
Vaish

**Comment by dougspeed** [comment]
Hi Vaish, thanks for trying LDAK, and you are very welcome to ask questions.

Based on your screenshot, it seems LDAK is set up correctly. When you typed ./ldak6.linux, LDAK started (it then immediately gave an error because no arguments were specified, but nonetheless it is working fine).

Therefore, you can now try some LDAK commands

E.g., if you type 
./ldak6.linux --linear output
then this is the start of a command for performing a simple linear regression 
(or otherwise, you can jump straight to trying to run LDAK-KVIK)

Thanks
Doug

**Comment by VaishMadh** [comment]
That's good to know! I was running the command using just ldak6 (as I would with plink), but after you mentioned it, I realized I need to use "./ldak6.linux". Now I have it up and running! Thanks for the help, Doug.
